theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: GastÃ³n H. Salazar Silva's CV

author:
	name   : "GastÃ³n Hugo Salazar Silva"
	email  : # optional
	uri    : "http://ghsalazar.github.io"

